### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by neopostmodern** [aroffringa/glight#458]
I wanted to try the software today, but failed building it. I'm not much of a C++ person, so this might be obvious to others.

- Which compiler and which version of it should I use? I tried gcc-11 and clang-15 without success.
- Do I need to configure any other options?

I'm currently on Ubuntu 22.04

The furthest I got (I think) was with clang-15 and no other options, but eventually it fails with
```
13 warnings generated.
13 warnings generated.
make[1]: *** [CMakeFiles/Makefile2:86: CMakeFiles/glight-object.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
```
But no error? I think?

**Comment by aroffringa** [comment]
Hi @neopostmodern , thanks for the report. The actual compilation error will be higher up in the output, but I could reproduce it on Ubuntu 22 and it was indeed an issue in the code: I had been a bit too forward with features of newer C++ standards that aren't yet fully supported in older gcc and clang versions. I've fixed this in #459, so that now on master it compiles fine with the default Ubuntu 22 version of gcc (which is gcc-11). Could you try again from master?

**Comment by neopostmodern** [comment]
Yup, now it works! Thank you.
Maybe add a note to the README to clarify this for future readers? (Theoretically it shouldn't be necessary to know this, but it would have helped me troubleshooting...)

**Comment by aroffringa** [comment]
Good idea; I've added gcc and Ubuntu version to the readme in #461 . Thanks for the feedback!
